version: "3.9"

volumes:
  remark42:

services:
  remark:
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      - REMARK_URL=http://localhost:8080
      - SITE=yesilmavihayat
      - DEBUG=true
      - AUTH_ANON=true
    volumes:
      - remark42:/srv/var
      - ./disqus-export.xml:/srv/var/disqus-export.xml
